name: APK Signature
description: Get signing certificate hash from APK input
inputs:
  path:
    description: Path to APK file
    required: true
outputs:
  signature:
    description: APK file signature
    value: ${{ steps.analysis.outputs.formattedSig }}

runs:
  using: composite
  steps:
    - shell: bash
      id: analysis
      env:
        APK_PATH: ${{ inputs.path }}
      run: |
        verification=$(${ANDROID_SDK_ROOT}/build-tools/37.0.0/apksigner verify --print-certs $APK_PATH 2>&1)
        echo $verification
        sha256=$(echo $verification | sed -n 's/.*SHA-256 digest: \([0-9a-fA-F]\{64\}\).*/\1/p' | head -1)
        echo "---"
        echo "SHA-256: $sha256"
        formattedSig=$(printf '%s' "$sha256" | tr '[:lower:]' '[:upper:]' | sed -E 's/(..)/\1:/g; s/:$//')
        echo "Formatted: $formattedSig"
        echo "formattedSig=$formattedSig" >> "$GITHUB_OUTPUT"
