name: Android App Submission
description: Submit a new app signature to the database
title: "[New]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a new app! Please make sure you edit the title above to include the app's name.
 
  - type: markdown
    attributes:
      value: |
        ## Submission

        This form is for apps you have **personally** checked in [AppVerifier](https://github.com/soupslurpr/AppVerifier).
        You will need AppVerifier to copy certain information from and paste in the fields below.

  - type: textarea
    id: verificationInfo
    attributes:
      label: Verification info
      description: |
        In AppVerifier, open the app you're submitting, click "Copy Verification Info" and then paste the resultant string exactly here.
      placeholder: |
        com.example.appname
        3A:04:A8:0B:2A:88:33:4C:...
      render: text
    validations:
      required: true

  - type: input
    id: directApkLink
    attributes:
      label: Direct download link
      description: |
        Optional. A direct HTTPS link to an APK file for this app (not a web page or store listing).
        This could be from GitHub releases, for example. If provided, we will check its signature in addition to mainstream app stores.
        Do **not** add a link to an APK from an F-Droid repo.
      placeholder: https://example.com/downloads/app.apk

  - type: input
    id: customFdroidRepo
    attributes:
      label: Custom F-Droid Repository
      description: |
        Optional. HTTPS URL to a developer-run F-Droid repository.
        If provided, we will check this repository for the app in addition to mainstream app stores.
      placeholder: https://example.com/fdroid/repo

  - type: input
    id: devVerification
    attributes:
      label: Signing key citation
      description: |
        Optional. Does the developer publish this key on an official website? Please link to that attestation if so, otherwise leave this blank.
      placeholder: https://github.com/example/app/README.md

  - type: markdown
    attributes:
      value: |
        ## Survey

        Some data about the source of your submission would be greatly appreciated.

  - type: dropdown
    id: appSource
    attributes:
      label: Submitted app source
      description: Where did you download the app you're submitting a hash for?
      options:
        - Google Play / Aurora Store
        - F-Droid
        - Accrescent
        - GitHub
        - GitLab
        - Codeberg
        - Developer's Website
        - Other

  - type: dropdown
    id: verifier
    attributes:
      label: Verifying app
      description: Where did you find the signature for this app?
      options:
        - Verified Apps (@privacyguides)
        - AppVerifier (@soupslurpr)
        - AppVerifierBG (@roundsalmon4)
        - apksigner CLI
        - Other

  - type: dropdown
    id: verifierSource
    attributes:
      label: Verifying app source
      description: Where did you download that verifying app?
      options:
        - Privacy Guides F-Droid Repo
        - Official F-Droid Repo
        - IzzyOnDroid F-Droid Repo
        - GitHub Releases
        - Accrescent
        - GrapheneOS App Store
        - Other download source
