name: Publish Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  download:
    uses: privacyguides/verified-apps/.github/workflows/create-artifact.yml@fb4058746d264f7ef5ba1f16dc40c499aeaf5a4d

  attest:
    needs: download
    uses: privacyguides/.github/.github/workflows/sign-artifact.yml@5c41b37a937aab5e50262f3ab672fc9b9438dbf9
    with:
      artifact-name: database
      artifact-path: data.yml

  release:
    needs: attest
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: database

      - name: Create release notes
        id: release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd
        with:
          artifacts: "data.yml"
          draft: true
