name: Sync to Mirrors

permissions:
  contents: read

on: [push, delete, create]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Codeberg
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACTIONS_SSH_KEY }}
        with:
          source-repo: "git@github.com:privacyguides/verified-apps.git"
          destination-repo: "git@codeberg.org:privacyguides/verified-apps.git"
